# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Book(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, title: str=None, author: str=None, year: int=None, genre: str=None):  # noqa: E501
        """Book - a model defined in Swagger

        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param year: The year of this Book.  # noqa: E501
        :type year: int
        :param genre: The genre of this Book.  # noqa: E501
        :type genre: str
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'year': int,
            'genre': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'year': 'year',
            'genre': 'genre'
        }

        self._title = title
        self._author = author
        self._year = year
        self._genre = genre

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this Book.

        Book title  # noqa: E501

        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.

        Book title  # noqa: E501

        :param title: The title of this Book.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.

        Author name  # noqa: E501

        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.

        Author name  # noqa: E501

        :param author: The author of this Book.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def year(self) -> int:
        """Gets the year of this Book.

        Publication year  # noqa: E501

        :return: The year of this Book.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this Book.

        Publication year  # noqa: E501

        :param year: The year of this Book.
        :type year: int
        """

        self._year = year

    @property
    def genre(self) -> str:
        """Gets the genre of this Book.

        Genre  # noqa: E501

        :return: The genre of this Book.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Book.

        Genre  # noqa: E501

        :param genre: The genre of this Book.
        :type genre: str
        """

        self._genre = genre
