# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Borrow(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: int=None, copy_id: int=None, return_date: str=None):  # noqa: E501
        """Borrow - a model defined in Swagger

        :param user_id: The user_id of this Borrow.  # noqa: E501
        :type user_id: int
        :param copy_id: The copy_id of this Borrow.  # noqa: E501
        :type copy_id: int
        :param return_date: The return_date of this Borrow.  # noqa: E501
        :type return_date: str
        """
        self.swagger_types = {
            'user_id': int,
            'copy_id': int,
            'return_date': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'copy_id': 'copy_id',
            'return_date': 'return_date'
        }

        self._user_id = user_id
        self._copy_id = copy_id
        self._return_date = return_date

    @classmethod
    def from_dict(cls, dikt) -> 'Borrow':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Borrow of this Borrow.  # noqa: E501
        :rtype: Borrow
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Borrow.

        User ID  # noqa: E501

        :return: The user_id of this Borrow.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Borrow.

        User ID  # noqa: E501

        :param user_id: The user_id of this Borrow.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def copy_id(self) -> int:
        """Gets the copy_id of this Borrow.

        Copy ID  # noqa: E501

        :return: The copy_id of this Borrow.
        :rtype: int
        """
        return self._copy_id

    @copy_id.setter
    def copy_id(self, copy_id: int):
        """Sets the copy_id of this Borrow.

        Copy ID  # noqa: E501

        :param copy_id: The copy_id of this Borrow.
        :type copy_id: int
        """

        self._copy_id = copy_id

    @property
    def return_date(self) -> str:
        """Gets the return_date of this Borrow.

        Return date in ISO format  # noqa: E501

        :return: The return_date of this Borrow.
        :rtype: str
        """
        return self._return_date

    @return_date.setter
    def return_date(self, return_date: str):
        """Sets the return_date of this Borrow.

        Return date in ISO format  # noqa: E501

        :param return_date: The return_date of this Borrow.
        :type return_date: str
        """

        self._return_date = return_date
